stages:
  - test

pytest:
  stage: test
  image: python:3.9
  script:
    - pip install -r requirements.txt
    - pytest --html=report.html --self-contained-html
  artifacts:
    paths:
      - report.html
